apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: "{{ .Values.mongoExpress.container.image.repository }}:{{ .Values.mongoExpress.container.image.tag }}"
          ports:
            - containerPort: {{ .Values.mongoExpress.container.port }}
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mongo-user
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mongo-password
            - name: ME_CONFIG_MONGODB_URL  #ME_CONFIG_MONGODB_SERVER
              value: mongodb://$(ME_CONFIG_MONGODB_ADMINUSERNAME):$(ME_CONFIG_MONGODB_ADMINPASSWORD)@mongodb-service:27017/admin?authSource=admin
              # valueFrom:
              #   configMapKeyRef:
              #     name: app-config
              #     key: mongo-url
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"  # Add this
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"   # Add this