apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-app-deployment
  labels:
    app: note-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: note-app
  template:
    metadata:
      labels:
        app: note-app
    spec:
      containers:
        - name: note-app
          image: "{{ .Values.noteApp.container.image.repository }}:{{ .Values.noteApp.container.image.tag }}"
          ports:
            - containerPort: {{ .Values.noteApp.container.port }}