apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  type:  {{ .Values.mongoExpress.service.type }}
  ports:
    - protocol: {{ .Values.mongoExpress.service.protocol }}
      port: {{ .Values.mongoExpress.service.port }}
      targetPort: {{ .Values.mongoExpress.service.targetPort }}
      nodePort: {{ .Values.mongoExpress.service.nodePort }}
  selector:
    app: mongo-express
