apiVersion: v1
kind: Service
metadata:
  name: note-server-service
  labels:
    app: note-server
spec:
  ports:
    - protocol: {{ .Values.noteServer.service.protocol }}
      port: {{ .Values.noteServer.service.port }}
      targetPort: {{ .Values.noteServer.service.targetPort }}
  selector:
    app: note-server
